=== servkey/actiongame-code/ac/docs/cubescriptreference.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="cubescriptreference">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="section">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="command">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="description" type="xs:string" />
                    <xs:element minOccurs="0" name="arguments">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="argument">
                            <xs:complexType>
                              <xs:attribute name="token" type="xs:string" use="required" />
                              <xs:attribute name="description" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== servkey/actiongame-code/ac/docs/editref.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="transformcubescript.xslt"?>


<cubescriptreference xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cubescriptreference.xsd">
  <section name="Editing Reference">
    <command name="edittoggle">
      <description><![CDATA[switches between map edit mode and normal (default key = e). In map edit mode you can select bits of the map by clicking or dragging your crosshair on the floor or ceiling (using the "attack" command, normally MOUSE1), then use the commands below to modify the selection. While in edit mode, physics & collision don't apply (noclip), and key repeat is ON. Note that if you fly outside the map, cube still renders the world as if you were standing on the floor directly below the camera.]]></description>
    </command>
    <command name="edittex">
      <description><![CDATA[Changes the texture on current selection by browsing through a list of textures directly shown on the cubes. T is an integer denoting the type (floor = 0, lower or wall = 1, ceiling = 2, upper wall = 3), D is the direction you want to cycle the textures in (1 = forwards, -1 = backwards). Default keys are the six keys above the cursor keys, which each 2 of them cycle one type (and numpad 7/4 for upper). The way this works is slightly strange at first, but allows for very fast texture assignment. All textures are in 3 individual lists for each type (both wall kinds treated the same), and each time a texture is used, it is moved to the top of the list. So after a bit of editing, all your most frequently used textures will come first when pressing these keys, and the most recently used texture is set immediately when you press the forward key for the type. These lists are saved with the map. make a selection (including wall bits) and press these keys to get a feel for what they do.]]></description>
      <arguments>
        <argument token="T" description="floor = 0, lower or wall = 1, ceiling = 2, upper wall = 3"/>
        <argument token="D" description="1 = forwards, -1 = backwards"/>
      </arguments>
    </command>
    <command name="editheight">
      <description><![CDATA[is the type as above (floors & ceilings only), and D is the delta value to move it in. Default keys are [ and ] for floor level, and o/p for ceiling.]]></description>
      <arguments>
        <argument token="T" description="floor = 0, lower or wall = 1, ceiling = 2"/>
        <argument token="D" description="direction to move in"/>
      </arguments>
    </command>
  </section>
</cubescriptreference>
